### ISSUE TITLE
Incorrect license

### ISSUE THREAD

**Issue by steveno** [grimwm/libballistics#1]
GEBC written by Derek Yates is licensed under the GNU GPLv2. You cannot re-license it to Apache 2.0 without his express written permission.

**Comment by grimwm** [comment]
I'll look at the legitimacy of that.  His source code doesn't include a
license.

**Comment by grimwm** [comment]
Looked again and saw one mention of it.  It did not specify a version nor
meet the requirements of GNU for licensing.  However, I've fixed the
license anyway.

**Comment by steveno** [comment]
The source code for the "library" version comes from [here](https://sourceforge.net/projects/balcomp/) which meets all the requirements for the GPL as far as I know.

**Comment by grimwm** [comment]
Per  https://www.gnu.org/licenses/gpl-howto.en.html, it does not look like
his license legally fits the definition.  He fails to meet many of the
requirements set forth in the 4th paragraph's bullet list.  And the origin
of my source code didn't come from sourceforge.  It's probably not
enforceable to have it as GPL, but I don't really care and made it GPLv2.
